name: HardcoreClaims
version: 2.0.1
description: Addon for Grief Prevention that deletes claims and restores the land when a player dies.
author: Alshain01
website: http://dev.bukkit.org/bukkit-plugins/hardcoreclaims/
main: io.github.alshain01.HardcoreClaims.HardcoreClaims
depend: [GriefPrevention]
softdepend: [Flags]
permissions:
  hardcoreclaims.admin:
    description: Allows a player to bypass container and command restrictions.
    default: false
