name: {$project.name}
version: {$project.version}
description: {$project.description}
author: {$project.author}
website: {$project.url}
main: {$project.main}
depend: [GriefPrevention]
softdepend: [Flags]
permissions:
  hardcoreclaims.admin:
    description: Allows a player to bypass container and command restrictions.
    default: false
